kind: pipeline
type: docker
name: default

clone:
  disable: true

workspace:
  path: /go/trytry

steps:

  - name: clone
    image: alpine/git
    volumes:
      - name: gopath
        path: /go
    commands:
      - cd ../
      - git chttps://github.com/LL-LeLouch/trytry.git

  - name: build
    image: lyumikael/gomodd:v1.0.0
    commands:
      - go mod tidy
      - modd

volumes:
  - name: gopath
    temp: {}

trigger:
  branch:
    - main

